name: Docker Build

on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: codr:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Docker image
        run: |
          docker build -t codr:test .
          docker run --rm \
            -e GITHUB_TOKEN=test_token \
            -e GITHUB_REPOS=testorg/repo1 \
            -e WEBHOOK_TOKEN=test_secret \
            -e PORT=8000 \
            codr:test python -c "from app.config import Settings; print('Config OK')"
